# Generated by Django 4.2 on 2026-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_user_cartitem_unique_user_product_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_product',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_session_product',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('session_key', 'product'), name='unique_session_product'),
        ),
    ]
