# Generated by Django 4.2 on 2026-06-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Terkirim')], default='processing', max_length=20),
        ),
    ]
