# Generated by Django 4.2 on 2026-06-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitem_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(choices=[('jne', 'JNE (Reguler)'), ('pos', 'POS Indonesia'), ('tiki', 'TIKI (Reguler)')], default='jne', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('qris', 'QRIS'), ('bank_transfer', 'Virtual Account (Transfer Bank)'), ('e_wallet', 'E-Wallet (GoPay/ShopeePay)')], default='qris', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('processing', 'Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Terkirim'), ('cancelled', 'Dibatalkan')], default='pending_payment', max_length=20),
        ),
    ]
