# Generated by Django 4.2 on 2026-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_courier_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Menunggu Pembayaran'), ('payment_verification', 'Menunggu Verifikasi Pembayaran'), ('processing', 'Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Terkirim'), ('cancelled', 'Dibatalkan')], default='pending_payment', max_length=20),
        ),
    ]
